export const SOCKET_EVENTS = {
  // Client → Server
  PARTY_JOIN: 'party:join',
  PARTY_LEAVE: 'party:leave',
  QUEUE_ADD: 'queue:add',
  QUEUE_VOTE: 'queue:vote',
  QUEUE_APPROVE: 'queue:approve',
  QUEUE_REJECT: 'queue:reject',
  QUEUE_REMOVE: 'queue:remove',
  PLAYBACK_PLAY: 'playback:play',
  PLAYBACK_PAUSE: 'playback:pause',
  PLAYBACK_SKIP: 'playback:skip',
  GUEST_MUTE: 'guest:mute',
  GUEST_UNMUTE: 'guest:unmute',
  GUEST_KICK: 'guest:kick',
  GUEST_BAN: 'guest:ban',
  PARTY_SETTINGS: 'party:settings',

  // Server → Client
  QUEUE_STATE: 'queue:state',
  QUEUE_ADDED: 'queue:added',
  QUEUE_REORDERED: 'queue:reordered',
  QUEUE_VOTED_OUT: 'queue:voted_out',
  QUEUE_REMOVED: 'queue:removed',
  QUEUE_PENDING: 'queue:pending',
  QUEUE_ITEM_LOCKED: 'queue:item_locked',
  PLAYBACK_UPDATE: 'playback:update',
  PLAYBACK_TRACK_CHANGED: 'playback:track_changed',
  GUEST_JOINED: 'guest:joined',
  GUEST_LEFT: 'guest:left',
  GUEST_STATUS: 'guest:status',
  PARTY_SETTINGS_UPDATED: 'party:settings_updated',
  TOAST: 'toast',
} as const;
